In [1]:
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# ===============================
# ARRAYS FROM SCRATCH VS GRADIENT
# ===============================

np.random.seed(0)
u = np.round(np.random.randn(6,6), 2)

dx = 0.01
dy = 0.01

print('Initial array \n', u)
print('\n')

# ===============================
# 1ST ORDER
# ===============================
dudx = np.zeros_like(u)
dudy = np.zeros_like(u)

# Calculate the y-axis gradient (dudy)
dudy[:, 1:-1] = (u[:, 2:] - u[:, :-2]) / (2 * dy)
dudy[:, 0] = (u[:, 1] - u[:, 0]) / dy
dudy[:, -1] = (u[:, -1] - u[:, -2]) / dy

# Calculate the x-axis gradient (dudx)
dudx[1:-1, :] = (u[2:, :] - u[:-2, :]) / (2 * dx)
dudx[0, :] = (u[1, :] - u[0, :]) / dx
dudx[-1, :] = (u[-1, :] - u[-2, :]) / dx


dudx_, dudy_ = np.gradient(u)
dudx_ = dudx_/dx
dudy_ = dudy_/dy

print('Using finite differences in x-axis \n', dudx)
print('Using np.gradient in x-axis \n', dudx_)

print('\n')

print('Using finite differences in y-axis \n', dudy)
print('Using np.gradient in y-axis \n', dudy_)

print('\n')

# ===============================
# 2ND ORDER
# ===============================
d2udx2 = np.zeros_like(u)
d2udy2 = np.zeros_like(u)

d2udx2[1:-1, 1:-1] = (u[2:, 1:-1] - 2 * u[1:-1, 1:-1] + u[:-2, 1:-1])/dx**2
d2udy2[1:-1, 1:-1] = (u[1:-1, 2:] - 2 * u[1:-1, 1:-1] + u[1:-1, :-2])/dy**2

dudt = d2udx2 + d2udy2

print("x-axis direction \n", d2udx2)
print('\n')
print("y-axis direction \n", d2udy2)
print('\n')
print("time derivative \n", dudt)

Initial array 
 [[ 1.76  0.4   0.98  2.24  1.87 -0.98]
 [ 0.95 -0.15 -0.1   0.41  0.14  1.45]
 [ 0.76  0.12  0.44  0.33  1.49 -0.21]
 [ 0.31 -0.85 -2.55  0.65  0.86 -0.74]
 [ 2.27 -1.45  0.05 -0.19  1.53  1.47]
 [ 0.15  0.38 -0.89 -1.98 -0.35  0.16]]


Using finite differences in x-axis 
 [[ -81.   -55.  -108.  -183.  -173.   243. ]
 [ -50.   -14.   -27.   -95.5  -19.    38.5]
 [ -32.   -35.  -122.5   12.    36.  -109.5]
 [  75.5  -78.5  -19.5  -26.     2.    84. ]
 [  -8.    61.5   83.  -131.5  -60.5   45. ]
 [-212.   183.   -94.  -179.  -188.  -131. ]]
Using np.gradient in x-axis 
 [[ -81.   -55.  -108.  -183.  -173.   243. ]
 [ -50.   -14.   -27.   -95.5  -19.    38.5]
 [ -32.   -35.  -122.5   12.    36.  -109.5]
 [  75.5  -78.5  -19.5  -26.     2.    84. ]
 [  -8.    61.5   83.  -131.5  -60.5   45. ]
 [-212.   183.   -94.  -179.  -188.  -131. ]]


Using finite differences in y-axis 
 [[-136.   -39.    92.    44.5 -161.  -285. ]
 [-110.   -52.5   28.    12.    52.   131. ]
 [ -64.  