In [1]:
import numpy as np

In [2]:
class Thermodynamics_DRM:
    
    def __init__(self, T, P, y, Mr, WBi_enthalpy, WBi_specific_heat, Hfi_298_species):
        
        self.T = T
        self.P = P
        self.y = y
        self.Mr = Mr
        self.WBi_enthalpy = WBi_enthalpy
        self.WBi_specific_heat = WBi_specific_heat
        self.Hfi_298_species = Hfi_298_species
        
###############################################################################################################################
    # literature information contained in the NIST SOURCE Data Archive - https://webbook.nist.gov/
    # CO2 + CH4 ⇌ 2CO + 2H2 - DRM reaction
    def enthalpy_drm_kj_mol(self):

        t = self.T/1000
        WBi = np.array([
              [25.56759,  6.096130,     4.054656,  -2.671301,  0.131021, -118.0089, 227.3665,   -110.5271],  # CO
              [-0.703029, 108.4773,    -42.52157,   5.862788,  0.678565, -76.84376, 158.7163,   -74.87310],  # CH4
              [24.99735,  55.18696,   -33.69137,    7.948387, -0.136638, -403.6075, 228.2431,   -393.5224],  # CO2
              [33.066178, -11.363417,  11.432816,  -2.772874, -0.158558, -9.980797, 172.707974,    0.0]      # H2
              ])

        # heats of formation at 298.15 K for 'CO', 'CH4', 'CO2', 'H2'
        Hfi_298 = np.array([-110.53, -74.85, -393.51, 0.0]) # kJ/mol

        Sfi_298 = np.array([197.66, 186.25, 213.79, 130.68]) # J/mol*K

        Stoichiometry = np.array([ 2,    # 'CO'
                                  -1,    # 'CH4'
                                  -1,    # 'CO2'
                                   2])   # 'H2'

        Hrxn298 = np.dot(Hfi_298, Stoichiometry)
        Srxn298 = np.dot(Sfi_298, Stoichiometry)
        Grxn298 = Hrxn298 - 298.15*(Srxn298)/1000

        T_Hi = np.array([t,  t**2 / 2.0, t**3 / 3.0, t**4 / 4.0, -1.0 / t, 1.0, 0.0, -1.0])
        T_Si = np.array([np.log(t), t,  t**2 / 2.0,  t**3 / 3.0, -1.0 / (2.0 * t**2), 0.0, 1.0, 0.0])

        Hi = np.dot(WBi, T_Hi)        # (H - H_298.15) kJ/mol
        Si = np.dot(WBi, T_Si/1000.0) # absolute entropy kJ/mol/K

        Hi_stoichiometry = Hi*Stoichiometry
        Si_stoichiometry = Si*Stoichiometry

        sum_Hi = sum(Hi_stoichiometry)
        sum_Si = sum(Si_stoichiometry)

        Hrxn = Hrxn298 + sum_Hi # kJ/mol
        Grxn = Hrxn - self.T*sum_Si

        R = 8.314e-3 # kJ/mol/K

        Keq = np.exp(-Grxn/R/self.T)

        return np.array([Hrxn])
    
###############################################################################################################################
    # literature information contained in the NIST SOURCE Data Archive - https://webbook.nist.gov/
    # CH4 + H2O ⇌ CO + 3H2 - SRM1 reaction
    def enthalpy_srm1_kj_mol(self): 

        t = self.T/1000            
        WBi = np.array([
              [25.56759,  6.096130,     4.054656,  -2.671301,  0.131021, -118.0089, 227.3665,   -110.5271],  # CO
              [-0.703029, 108.4773,    -42.52157,   5.862788,  0.678565, -76.84376, 158.7163,   -74.87310],  # CH4
              [30.09200,  6.832514,     6.793435,  -2.534480,  0.082139, -250.8810, 223.3967,   -241.8264],  # H2O
              [33.066178, -11.363417,  11.432816,  -2.772874, -0.158558, -9.980797, 172.707974,    0.0]      # H2
              ])


        # heats of formation at 298.15 K for 'CO', 'CH4', 'H2O', 'H2'
        Hfi_298 = np.array([-110.53, -74.85, -241.826, 0.0]) # kJ/mol

        Sfi_298 = np.array([197.66, 186.25, 188.84, 130.68]) # J/mol*K

        Stoichiometry = np.array([ 1,    # 'CO'
                                  -1,    # 'CH4'
                                  -1,    # 'H2O'
                                   3])   # 'H2'

        Hrxn298 = np.dot(Hfi_298, Stoichiometry)
        Srxn298 = np.dot(Sfi_298, Stoichiometry)
        Grxn298 = Hrxn298 - 298.15*(Srxn298)/1000

        T_Hi = np.array([t,  t**2 / 2.0, t**3 / 3.0, t**4 / 4.0, -1.0 / t, 1.0, 0.0, -1.0])
        T_Si = np.array([np.log(t), t,  t**2 / 2.0,  t**3 / 3.0, -1.0 / (2.0 * t**2), 0.0, 1.0, 0.0])

        Hi = np.dot(WBi, T_Hi)        # (H - H_298.15) kJ/mol
        Si = np.dot(WBi, T_Si/1000.0) # absolute entropy kJ/mol/K

        Hi_stoichiometry = Hi*Stoichiometry
        Si_stoichiometry = Si*Stoichiometry

        sum_Hi = sum(Hi_stoichiometry)
        sum_Si = sum(Si_stoichiometry)

        Hrxn = Hrxn298 + sum_Hi # kJ/mol
        Grxn = Hrxn - self.T*sum_Si

        R = 8.314e-3 # kJ/mol/K

        Keq = np.exp(-Grxn/R/self.T)
        
        return np.array([Hrxn])
    
###############################################################################################################################     
    # literature information contained in the NIST SOURCE Data Archive - https://webbook.nist.gov/
    # CH4 + 2H2O ⇌ CO2 + 4H2 - SRM2 reaction
    def enthalpy_srm2_kj_mol(self):

        t = self.T/1000                  
        WBi = np.array([
              [24.99735,  55.18696,   -33.69137,    7.948387, -0.136638, -403.6075, 228.2431,   -393.5224],  # CO2
              [-0.703029, 108.4773,    -42.52157,   5.862788,  0.678565, -76.84376, 158.7163,   -74.87310],  # CH4
              [30.09200,  6.832514,     6.793435,  -2.534480,  0.082139, -250.8810, 223.3967,   -241.8264],  # H2O
              [33.066178, -11.363417,  11.432816,  -2.772874, -0.158558, -9.980797, 172.707974,    0.0]      # H2
              ])


        # heats of formation at 298.15 K for 'CO2', 'CH4', 'H2O', 'H2'
        Hfi_298 = np.array([-393.51, -74.85, -241.826, 0.0]) # kJ/mol

        Sfi_298 = np.array([213.79, 186.25, 188.84, 130.68]) # J/mol*K

        Stoichiometry = np.array([ 1,    # 'CO2'
                                  -1,    # 'CH4'
                                  -2,    # 'H2O'
                                   4])   # 'H2'

        Hrxn298 = np.dot(Hfi_298, Stoichiometry)
        Srxn298 = np.dot(Sfi_298, Stoichiometry)
        Grxn298 = Hrxn298 - 298.15*(Srxn298)/1000

        T_Hi = np.array([t,  t**2 / 2.0, t**3 / 3.0, t**4 / 4.0, -1.0 / t, 1.0, 0.0, -1.0])
        T_Si = np.array([np.log(t), t,  t**2 / 2.0,  t**3 / 3.0, -1.0 / (2.0 * t**2), 0.0, 1.0, 0.0])

        Hi = np.dot(WBi, T_Hi)        # (H - H_298.15) kJ/mol
        Si = np.dot(WBi, T_Si/1000.0) # absolute entropy kJ/mol/K

        Hi_stoichiometry = Hi*Stoichiometry
        Si_stoichiometry = Si*Stoichiometry

        sum_Hi = sum(Hi_stoichiometry)
        sum_Si = sum(Si_stoichiometry)

        Hrxn = Hrxn298 + sum_Hi # kJ/mol
        Grxn = Hrxn - self.T*sum_Si

        R = 8.314e-3 # kJ/mol/K

        Keq = np.exp(-Grxn/R/self.T)

        return np.array([Hrxn])

###############################################################################################################################
    # literature information contained in the NIST SOURCE Data Archive - https://webbook.nist.gov/
    # CO + H2O ⇌ CO2 + H2 - WGS reaction
    def enthalpy_wgs_kj_mol(self):   

        t = self.T/1000                 
        WBi = np.array([
              [25.56759,  6.096130,     4.054656,  -2.671301,  0.131021, -118.0089, 227.3665,   -110.5271],  # CO
              [30.09200,  6.832514,     6.793435,  -2.534480,  0.082139, -250.8810, 223.3967,   -241.8264],  # H2O
              [24.99735,  55.18696,   -33.69137,    7.948387, -0.136638, -403.6075, 228.2431,   -393.5224],  # CO2
              [33.066178, -11.363417,  11.432816,  -2.772874, -0.158558, -9.980797, 172.707974,    0.0]      # H2
              ])


        # heats of formation at 298.15 K for 'CO', 'H2O', 'CO2', 'H2'
        Hfi_298 = np.array([-110.53, -241.826, -393.51, 0.0]) # kJ/mol

        Sfi_298 = np.array([197.66, 188.84, 213.79, 130.68]) # J/mol*K

        Stoichiometry = np.array([-1,    # 'CO'
                                  -1,    # 'H2O'
                                   1,    # 'CO2'
                                   1])   # 'H2'

        Hrxn298 = np.dot(Hfi_298, Stoichiometry)
        Srxn298 = np.dot(Sfi_298, Stoichiometry)
        Grxn298 = Hrxn298 - 298.15*(Srxn298)/1000

        T_Hi = np.array([t,  t**2 / 2.0, t**3 / 3.0, t**4 / 4.0, -1.0 / t, 1.0, 0.0, -1.0])
        T_Si = np.array([np.log(t), t,  t**2 / 2.0,  t**3 / 3.0, -1.0 / (2.0 * t**2), 0.0, 1.0, 0.0])

        Hi = np.dot(WBi, T_Hi)        # (H - H_298.15) kJ/mol
        Si = np.dot(WBi, T_Si/1000.0) # absolute entropy kJ/mol/K

        Hi_stoichiometry = Hi*Stoichiometry
        Si_stoichiometry = Si*Stoichiometry

        sum_Hi = sum(Hi_stoichiometry)
        sum_Si = sum(Si_stoichiometry)

        Hrxn = Hrxn298 + sum_Hi # kJ/mol
        Grxn = Hrxn - self.T*sum_Si

        R = 8.314e-3 # kJ/mol/K

        Keq = np.exp(-Grxn/R/self.T)

        return np.array([Hrxn])
    
 ###############################################################################################################################   
    def partial_enthalpies_kj_mol(self):

        t = self.T/1000

        T_Hi = np.array([t,  t**2 / 2.0, t**3 / 3.0, t**4 / 4.0, -1.0 / t, 1.0, 0.0, -1.0])

        Hi = self.WBi_enthalpy@T_Hi # (H - H_298.15) kJ/mol

        return np.array([(Hi + self.Hfi_298_species)]) # kJ/mol

###############################################################################################################################
    def ci_mol_m3(self):

        return np.array([self.y*self.P/(8.314e-05*self.T)]) # mol/m3
    
    def c_total_mol_m3(self):

        return np.array([sum(self.y*self.P/(8.314e-05*self.T))]) # mol/m3
    
    def d_mix_kg_m3(self):
        
        return np.array([np.sum(self.y*self.P/(8.314e-05*self.T))*np.dot(self.Mr, self.y)]) # kg/m3
    
    def mr_mix_kg_mol(self):
        
        return np.array([np.dot(self.Mr, self.y)]) # kg/mol

###############################################################################################################################
    # specific heat capacity of species
    def cpi_j_mol_K(self):

        t = self.T/1000

        T_Cpi = np.array([1,  t, t**2, t**3, 1.0/t])

        return np.array([np.dot(self.WBi_specific_heat, T_Cpi)]) # in J/mol/K for p = 1 bar
   
    # specific heat capacity of the mixture
    def cp_mix_j_mol_K(self):

        t = self.T/1000

        T_Cpi = np.array([1,  t, t**2, t**3, 1.0/t])

        return np.array([(np.dot(np.dot(self.WBi_specific_heat, T_Cpi), self.y)).sum()]) # J/mol/K for p = 1 bar
    
    # specific heat capacity of the mixture
    def cp_mix_kg_mol_K(self):

        t = self.T/1000

        T_Cpi = np.array([1,  t, t**2, t**3, 1.0/t])

        return np.array([(np.dot(np.dot(self.WBi_specific_heat, 
                                        T_Cpi), self.y)).sum()/np.dot(self.Mr, self.y)]) # J/kg/K for p = 1 bar

In [3]:
# define the mixture composition and thermodynamic conditions (i.e., T, P, molar ratio, Mr, Nist Data)

species = np.array(["CH4", "CO2", "H2O", "H2", "CO", "Ar"])
T = 873.15 # K
P = 1 # bar
y = np.array([0.3, 0.2, 0.0, 0.0, 0.0, 0.5]) # dimensionless
Mr = np.array([16.04e-03, 44.01e-03, 18.01528e-03, 2*1.00794e-03, 28.01e-03, 39.948e-03]) # kg/mol

WBi_enthalpy = np.array([
  [-0.703029, 108.4773,      -42.52157,       5.862788,      0.678565,    -76.84376,  158.7163,   -74.87310],  # CH4  
  [24.99735,   55.18696,     -33.69137,       7.948387,     -0.136638,   -403.6075,   228.2431,  -393.5224],   # CO2
  [30.09200,    6.832514,      6.793435,     -2.534480,      0.082139,   -250.8810,   223.3967,  -241.8264],   # H2O
  [33.066178, -11.363417,     11.432816,     -2.772874,     -0.158558,     -9.980797, 172.707974,   0.00000],  # H2
  [25.56759,    6.096130,      4.054656,     -2.671301,      0.131021,   -118.0089,   227.3665,  -110.52710],  # CO    
  [20.78600,    2.825911e-07, -1.464191e-07,  1.092131e-08, -3.661371e-08, -6.197350, 179.9990,     0.00000],  # Ar
  ])

WBi_specific_heat = np.array([
  [-0.703029, 108.4773,     -42.52157,       5.862788,       0.678565],       # CH4  
  [24.99735,   55.18696,    -33.69137,       7.948387,      -0.136638],       # CO2
  [30.09200,    6.832514,     6.793435,     -2.534480,       0.082139],       # H2O
  [25.56759,    6.096130,     4.054656,     -2.671301,       0.131021],       # CO
  [33.066178, -11.363417,    11.432816,     -2.772874,      -0.158558],       # H2    
  [20.78600,    2.825911e-07, -1.464191e-07,  1.092131e-08, -3.661371e-08],   # Ar
  ])

# heats of formation at 298.15 K for 'CH4', 'CO2', 'H2O', 'H2', 'CO', 'Ar' in kJ/mol
Hfi_298 = np.array([-74.85, -393.51, -241.826,  0.0, -110.53, 0.0])

In [5]:
# define the mixture composition and thermodynamic conditions
thermo = Thermodynamics_DRM(T, P, y, Mr, WBi_enthalpy, WBi_specific_heat, Hfi_298)

In [6]:
# enthalpy of drm in kJ/mol
thermo.enthalpy_drm_kj_mol()[0]

260.0853040432239

In [7]:
# enthalpy of srm1 in kJ/mol
thermo.enthalpy_srm1_kj_mol()[0]

224.02235379865817

In [8]:
# enthalpy of srm2 in kJ/mol
thermo.enthalpy_srm2_kj_mol()[0]

187.95940355409243

In [9]:
# enthalpy of wgs in kJ/mol
thermo.enthalpy_wgs_kj_mol()[0]

-36.06295024456574

In [10]:
# partial enthalpies of species in kJ/mol
thermo.partial_enthalpies_kj_mol()[0]

array([ -45.44395579, -366.89608539, -220.95618251,   16.87479203,
        -93.0021606 ,   11.95194602])

In [11]:
# partial concentrations of species in mol/m3
thermo.ci_mol_m3()[0]

array([4.13259053, 2.75506035, 0.        , 0.        , 0.        ,
       6.88765088])

In [12]:
# total concentration of ideal mixture in mol/m3
thermo.c_total_mol_m3()[0]

13.775301768303807

In [13]:
# molar mass of ideal gas mixture in kg/mol
thermo.mr_mix_kg_mol()[0]

0.033588

In [14]:
# density of ideal gas mixture in kg/m3
thermo.d_mix_kg_m3()[0]

0.4626848357937883

In [15]:
# partial molar specific heat capacity in J/mol/K
thermo.cpi_j_mol_K()[0]

array([66.27576278, 52.63245614, 39.64397803, 32.35347837, 29.83304121,
       20.7860001 ])

In [16]:
# specific heat capacity of the mixture in J/mol/K
thermo.cp_mix_j_mol_K()[0]

40.80222011142341

In [17]:
# specific heat capacity of the mixture in J/kg/K
thermo.cp_mix_kg_mol_K()[0]

1214.7856410451177