# Jacobi Method

### Element-based formula
$$x^{k+1}_i = \frac{1}{A_{ii}} \left(b_i - \sum_{j≠i} A_{ij} x^{k}_j \right), i = 1,2,...,n$$

### Matrix notation
$$ x^{k+1} = D^{-1}(b - Rx^k) $$

In [1]:
import numpy as np

"""
4x + 2y – 2z = 0
x – 3y – z = 7
3x – y + 4z = 5
"""

import numpy as np


def jacobi(A, b, N=25, x=None, tol=1e-6):
  if x is None:
    x = np.zeros(len(A[0]))

 # Create a vector of the diagonal elements and substract them from A
  D = np.diag(A)
  R = A - np.diagflat(D)

  for k in range(N):
    x_old = x.copy()
    r = b - (R @ x)
    x = r / D

    # Calculate the change in the solution vector
    """The Jacobi method uses a global change measurement because it updates
    all components of `x simultaneously, and it checks how much the entire
    solution vector has changed."""
    change = np.linalg.norm(x - x_old)

    # Check if the change is below the tolerance
    if change < tol:
      print(f"Converged after {k + 1} iterations.")
      return x

  print("Did not converge within the maximum number of iterations.")
  return x

A = np.array([[4.0, 2.0, -2.0],
              [1.0, -3.0, -1.0],
              [3.0, -1.0, 4.0]])

b = np.array([0.0, 7.0, 5.0])

sol = jacobi(A, b, N=100)

print("Solution x:")
print(sol)

print("Error")
print(A @ sol - b)

Converged after 68 iterations.
Solution x:
[ 9.99999500e-01 -1.99999984e+00  1.91691871e-07]
Error
[-2.05977863e-06 -1.17362351e-06 -8.92552191e-07]


### Gauss-Seidel

### Element-based formula
$$x^{k+1}_i = \frac{1}{A_{ii}} \left(b_i - \sum_{j=1}^{i-1} A_{ij} x^{k+1}_j - \sum_{j=i+1}^{n} A_{ij} x^k_j\right), i = 1,2,...,n$$

### Matrix notation

$$x^{k+1} = x^{k} + E^{-1} (b - Ax^{k})$$

where $E$ is the lower triangle matrix

In [2]:
import numpy as np

def gauss_seidel(A, b, num_steps=25, x=None, tol=1e-6):
    if x is None:
        x = np.zeros(len(A[0]))

    # Lower triangle of an array.
    E = np.tril(A)

    for k in range(num_steps):
        r = b - A @ x
        x = x + np.linalg.inv(E) @ r

        """The Gauss-Seidel method uses a local change measurement because it
        updates components of x sequentially, and it checks how well each
        equation is being satisfied by measuring the change in the residual
        vector, which reflects the local error in each equation."""
        change = np.linalg.norm(r)

        if change < tol:
            print(f"Converged after {k + 1} iterations.")
            return x

    print("Did not converge within the maximum number of iterations.")
    return x

A = np.array([[4.0, 2.0, -2.0],
              [1.0, -3.0, -1.0],
              [3.0, -1.0, 4.0]])

b = np.array([0.0, 7.0, 5.0])

sol = gauss_seidel(A, b, num_steps=100)

print("Solution x:")
print(sol)

print("Error")
print(A @ sol - b)

Converged after 17 iterations.
Solution x:
[ 1.00000007e+00 -1.99999999e+00 -4.97728368e-08]
Error
[4.02007540e-07 8.65312284e-08 0.00000000e+00]
