In [1]:
import numpy as np
import pandas as pd

In [79]:
molecules = ['H2S', 'CH4']

dic = {'molar_ratio': [1, 100], 
        'molar_mass': [34.01, 16.04], 
        'mg_g': [100, 50]}

df = pd.DataFrame(dic, index = molecules)
df

molar_ratio  molar_mass  mg_g
H2S            1       34.01   100
CH4          100       16.04    50

In [80]:
molar_ratio = df['molar_ratio'].values
molar_ratio

array([  1, 100], dtype=int64)

In [81]:
mmol_g = (df["mg_g"]/df["molar_mass"]).values
mmol_g

array([2.94031167, 3.11720698])

In [82]:
ads_ratio = mmol_g/mmol_g.sum()
ads_ratio

array([0.4853987, 0.5146013])

In [83]:
ratio = ads_ratio/molar_ratio
ratio

array([0.4853987 , 0.00514601])

In [85]:
# Horizontal flip
sel = np.diag(np.fliplr(ratio.reshape([-1,1])/ratio.reshape([1,-1])))
sel

array([9.43251985e+01, 1.06016209e-02])

In [86]:
print("for", molecules[0], "selectivity is", sel[0])
print("for", molecules[1], "selectivity is", sel[1])

for H2S selectivity is 94.32519847103792
for CH4 selectivity is 0.010601620947630924
